#2198 - export-download-query-reports
inception-project/inception pull request #2387
Opened 2021-06-17 16:55 UTC by Falko1

- created class TestResultsExporter in ui sidebar with export and import function (the latter is for test purposes)
- created test class TestResultsExporterTest in ui sidebar for class TestResultsExporter

**What's in the PR**
* ...

**How to test manually**
* ...

**Automatic testing**
* [ ] PR includes unit tests

**Documentation**
* [ ] PR updates documentation

2021-06-17 17:37 UTC, jcklie commented
I know it is only a first commit, but please adhere to the Dkpro style we use, especially:

- In function arguments, prefix things with a, .e.g `aFilePath`
- Use the [automated formatting ](https://zoidberg.ukp.informatik.tu-darmstadt.de/jenkins/view/INCEpTION/job/INCEpTION%20(GitHub)%20(master)%20-%20Docker/de.tudarmstadt.ukp.inception.app$inception-app-webapp/doclinks/3/#_checkstyle_and_formatting_2)

2021-06-30 10:16 UTC, jcklie requested changes
- The file has no file ending when I download it
- Maybe we want to add begin and end offsets to the csv
- Maybe we want more context

2021-07-05 15:53 UTC, jcklie commented on inception/inception-ui-search/pom.xml
> +            <version>9.3.0</version>
You should not put a version here, the version comes from the parent pom

2021-07-05 15:53 UTC, jcklie commented on inception/inception-ui-search/pom.xml
> +            <artifactId>junit-jupiter-api</artifactId>
You need test scope here, otherwise you compile junit into the resulting binary

2021-07-05 15:54 UTC, jcklie commented on inception/inception-ui-search/pom.xml
> +
Lots of whitespace

2021-07-05 15:54 UTC, jcklie commented on inception/inception-ui-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/search/sidebar/SearchAnnotationSidebar.java
> +        AjaxDownloadLink exportButton = new AjaxDownloadLink("export", () -> "searchResults.txt",
I would name it ".csv" so that excel knows whats up

2021-07-09 18:09 UTC, reckart approved these changes
Nice work! Thanks 👍

2021-07-09 19:56 UTC, merged